"""Snapshot-scoped element references — the ``block:27`` / ``link:12`` contract.

An agent never receives a CSS selector, a DOM node, or a Playwright handle.
It receives a :class:`SnapshotRef`: a typed, opaque-to-the-page handle onto
one element of one :class:`~webglass.pages.PageSnapshot`. Issue #1 section 5
makes the scoping rule non-negotiable:

    Element references are valid only for the snapshot/session generation
    that produced them — a stale reference must fail clearly rather than hit
    a different element.

So every reference carries its own scope (``snapshot_id`` + ``generation``),
and :meth:`SnapshotRef.require_scope` is the one place that decides whether a
reference may be applied to a snapshot. There is no "best effort" path: a
mismatch raises :class:`StaleReferenceError`, never a silent re-resolution
against whatever now happens to sit at that index.

Two textual forms exist, and the difference is deliberate:

``block:27`` (:attr:`SnapshotRef.short`)
    The agent-facing form. Compact, and unambiguous *because* it is always
    read alongside the snapshot that owns it (its payload carries
    ``snapshot_id`` / ``generation`` at the top level).

``snap-a@3/block:27`` (:attr:`SnapshotRef.qualified`)
    The self-scoping form, used whenever a reference outlives a single
    payload — a read cursor handed back to a later CLI invocation, an
    evidence citation, a log line. Parsing it needs no external context.

Trust zones (issue #1 section 7): a reference is *trusted control metadata*
generated by WebGlass. It never contains page-supplied text, so it can safely
be echoed back into logs and error messages.

This module imports nothing from the rest of ``webglass`` — it is the bottom
of the page/extraction stack.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum

__all__ = [
    "RefKind",
    "ReferenceSyntaxError",
    "SnapshotRef",
    "SnapshotReferenceError",
    "StaleReferenceError",
    "UnknownReferenceError",
    "parse_qualified_ref",
    "parse_ref",
    "validate_snapshot_id",
]

STALE_REMEDIATION = (
    "re-open or re-read the page and use the references from the new snapshot; "
    "references are valid only for the snapshot generation that issued them"
)


class RefKind(StrEnum):
    """The element families a snapshot can hand out references to."""

    BLOCK = "block"
    LINK = "link"
    FIELD = "field"
    FORM = "form"
    BUTTON = "button"


class SnapshotReferenceError(Exception):
    """Base for every reference failure; carries an agent-actionable remediation.

    Deliberately *not* a ``CliError``: this module sits below the CLI, and the
    CLI layer is responsible for translating these into the
    ``{code, message, remediation}`` error contract. Keeping the mapping at
    the boundary is what lets the library and the CLI share one implementation
    (issue #1 section 1) without the core importing CLI plumbing.
    """

    def __init__(self, message: str, *, remediation: str = "") -> None:
        super().__init__(message)
        self.message = message
        self.remediation = remediation


class StaleReferenceError(SnapshotReferenceError):
    """A reference was applied outside the snapshot generation that issued it."""

    def __init__(
        self,
        message: str,
        *,
        remediation: str = STALE_REMEDIATION,
        ref: SnapshotRef | None = None,
    ) -> None:
        super().__init__(message, remediation=remediation)
        self.ref = ref


class UnknownReferenceError(SnapshotReferenceError):
    """A correctly scoped reference names nothing in this snapshot."""


class ReferenceSyntaxError(SnapshotReferenceError, ValueError):
    """A reference (or a snapshot id) is not well formed."""


# A snapshot id must never contain the delimiters of the qualified form, or
# ``snap@1/block:2`` would stop round-tripping.
_SNAPSHOT_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
_SHORT_RE = re.compile(r"^(?P<kind>[a-z]+):(?P<index>[0-9]+)$")
_QUALIFIED_RE = re.compile(
    r"^(?P<snapshot_id>[A-Za-z0-9][A-Za-z0-9._-]*)"
    r"@(?P<generation>[0-9]+)"
    r"/(?P<kind>[a-z]+):(?P<index>[0-9]+)$"
)


def validate_snapshot_id(snapshot_id: str) -> str:
    """Return ``snapshot_id`` if it is usable in a qualified reference, else raise."""
    if not isinstance(snapshot_id, str) or not _SNAPSHOT_ID_RE.match(snapshot_id):
        raise ReferenceSyntaxError(
            f"invalid snapshot id {snapshot_id!r}",
            remediation=(
                "snapshot ids must be non-empty and use only letters, digits, "
                "'.', '_' and '-' (no '@', '/', ':' or whitespace)"
            ),
        )
    return snapshot_id


def _validate_kind(kind: RefKind | str) -> RefKind:
    try:
        return RefKind(kind)
    except ValueError as exc:
        known = ", ".join(k.value for k in RefKind)
        raise ReferenceSyntaxError(
            f"unknown reference kind {str(kind)!r}",
            remediation=f"use one of: {known}",
        ) from exc


def _validate_count(value: int, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise ReferenceSyntaxError(
            f"{label} must be a non-negative integer, got {value!r}",
            remediation=f"pass a non-negative integer {label}",
        )
    return value


@dataclass(frozen=True, slots=True)
class SnapshotRef:
    """A typed handle onto one element of one snapshot generation.

    Immutable and hashable, so references can be used as dict/set keys and
    compared for identity of *target*, not of object.
    """

    snapshot_id: str
    generation: int
    kind: RefKind
    index: int

    def __post_init__(self) -> None:
        validate_snapshot_id(self.snapshot_id)
        object.__setattr__(self, "generation", _validate_count(self.generation, "generation"))
        object.__setattr__(self, "kind", _validate_kind(self.kind))
        object.__setattr__(self, "index", _validate_count(self.index, "index"))

    @property
    def short(self) -> str:
        """The agent-facing form, e.g. ``block:27``."""
        return f"{self.kind.value}:{self.index}"

    @property
    def qualified(self) -> str:
        """The self-scoping form, e.g. ``snap-a@3/block:27``."""
        return f"{self.snapshot_id}@{self.generation}/{self.short}"

    def __str__(self) -> str:  # pragma: no cover - trivial delegation
        return self.qualified

    def scoped_to(self, snapshot_id: str, generation: int) -> bool:
        """Whether this reference belongs to the given snapshot generation."""
        return self.snapshot_id == snapshot_id and self.generation == generation

    def require_scope(self, snapshot_id: str, generation: int) -> None:
        """Raise :class:`StaleReferenceError` unless this reference is in scope."""
        if not self.scoped_to(snapshot_id, generation):
            raise StaleReferenceError(
                f"reference {self.qualified!r} does not belong to snapshot "
                f"{snapshot_id!r} generation {generation}",
                ref=self,
            )

    def to_dict(self) -> dict[str, object]:
        return {
            "snapshot_id": self.snapshot_id,
            "generation": self.generation,
            "kind": self.kind.value,
            "index": self.index,
            "ref": self.short,
        }


def parse_ref(text: str, *, snapshot_id: str, generation: int = 0) -> SnapshotRef:
    """Parse the short form ``kind:index`` into a reference in the given scope.

    The scope is supplied by the caller and never read out of ``text`` — a
    short reference that smuggles in a qualified form is rejected rather than
    silently re-scoped.
    """
    match = _SHORT_RE.match(text or "")
    if match is None:
        raise ReferenceSyntaxError(
            f"malformed reference {text!r}",
            remediation="use the '<kind>:<index>' form, e.g. 'block:27'",
        )
    return SnapshotRef(
        snapshot_id=snapshot_id,
        generation=generation,
        kind=_validate_kind(match.group("kind")),
        index=int(match.group("index")),
    )


def parse_qualified_ref(text: str) -> SnapshotRef:
    """Parse the self-scoping form ``snapshot@generation/kind:index``."""
    match = _QUALIFIED_RE.match(text or "")
    if match is None:
        raise ReferenceSyntaxError(
            f"malformed qualified reference {text!r}",
            remediation=(
                "use the '<snapshot-id>@<generation>/<kind>:<index>' form, "
                "e.g. 'snap-a@3/block:27'"
            ),
        )
    return SnapshotRef(
        snapshot_id=match.group("snapshot_id"),
        generation=int(match.group("generation")),
        kind=_validate_kind(match.group("kind")),
        index=int(match.group("index")),
    )
